# Site settings
site: Emma May Photography
email: info@emmamayphotography.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emmamayphotography.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
